

```{r}
ibrary(data.table)
library(stringr)
library(reshape2)
library(pheatmap)

library(caret)
library(ggplot2)
library(glmnet)
library(doParallel)
library(ROCR)
library(pROC)
library(Matrix)
library(sva)
library("randomForest")
library(xgboost)


mytemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(colour = "black"),axis.text.y =element_text(colour = "black"),
              axis.title.y=element_text(colour = "black"))
widetemp<-theme(panel.background=element_rect(fill="white",colour=NA), panel.grid.major =element_blank(), panel.grid.minor = element_blank(),axis.line = element_line(colour = "black",size=0.5),axis.text.x = element_text(angle = 30,size = 12,hjust = 1,colour = "black"),axis.text.y =element_text(size = 12,colour = "black"),
                axis.title.y=element_text(size=12,colour = "black"),legend.text=element_text(size=12))

basecol<-function(n){
  colall<-c('#d7191c','#31a354','#756bb1','#0571b0','#d95f0e','#bdbdbd')
  return(colall[c(1:n)])
}
pc_col<-function(n){
  colall<-c('#a6cee3','#1f78b4','#fee08b','#bf812d','#fb9a99','#e31a1c')
  return(colall[c(1:n)])
}

```

```{r}

res_tab<-read.table("../../early_test_model/final/valid_v2p.tsv",sep='\t',header = T,row.names = 1)
rownames(res_tab)<-str_sub(row.names(res_tab),start=7)

sample_info_v2<-read.table("../config/v2p_sample_info_1212.txt",sep='\t',header = T)
sample_info_v2$PSA<-as.numeric(sample_info_v2$PSA)
rownames(sample_info_v2)<-sample_info_v2$Index

res_tab<-cbind(res_tab,sample_info_v2[rownames(res_tab),c(1:6,10)])

res_tab3<-subset(res_tab2,PSA>4 & PSA<20)


pred <- prediction(as.numeric(as.matrix(res_tab2$score)), res_tab2$group)
perf <- performance(pred,"tpr","fpr")
roc_obj<-roc(res_tab2$group,as.numeric(res_tab2$score))
ci_roc<-ci(roc_obj)

plot_tab1<- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),ROC=paste0("PCa test score for all samples (23),",round(ci_roc[2],3)," (",round(ci_roc[1],3),"-",round(ci_roc[3],3),')'))


pred <- prediction(as.numeric(as.matrix(res_tab3$score)), res_tab3$group)
perf <- performance(pred,"tpr","fpr")
roc_obj<-roc(res_tab3$group,as.numeric(res_tab3$score))
ci_roc<-ci(roc_obj)

plot_tab2<- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),ROC=paste0("PCa test score for PSA 4-20 samples(15),\n",round(ci_roc[2],3)," (",round(ci_roc[1],3),"-",round(ci_roc[3],3),')'))



pred <- prediction(as.numeric(as.matrix(res_tab3$PSA)), res_tab3$group)
perf <- performance(pred,"tpr","fpr")
roc_obj<-roc(res_tab3$group,as.numeric(res_tab3$PSA))
ci_roc<-ci(roc_obj)

plot_tab3<- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),ROC=paste0("PSA for PSA 4-20 samples(15),\n",round(ci_roc[2],3)," (",round(ci_roc[1],3),"-",round(ci_roc[3],3),')'))

plot_tab<-rbind(plot_tab1,plot_tab2,plot_tab3)


p<-ggplot(plot_tab,aes(x=FPR,y=TPR,col=ROC))+geom_line()+scale_color_manual(NULL,values=c(basecol(3)))+mytemp
p
ggsave(p,filename = "../final/figure/pub/figure4b.pdf",height=4,width=7)


res_tab2$group<-factor(res_tab2$group,labels = c("non-cancer","non-meta"))
p<-ggplot(res_tab2,aes(x=as.factor(group),y=score,col=group))+geom_jitter(width=0.2)+mytemp+ylim(c(0,1.001))+xlab(NULL)+scale_color_manual(values=c("blue",'red'))
p
ggsave(p,filename = "../final/figure/pub/figure4c.pdf",width = 5,height = 4)


out_res2<-read.table("../final/all_early_late_sample_prediction.tsv",sep = "\t",header = T)
tmp<-out_res2[,c(10,11)]
tmp<-subset(tmp,group2!="unknown")
tmp$group2[tmp$group2!="non_meta"]<-"meta"
p<-ggplot(tmp,aes(x=group2,y=out_res.comb_pred/2,col=group2))+geom_jitter(width=0.2,size=0.8)+mytemp+ylim(c(0,1))+xlab(NULL)+ylab("score")+scale_color_manual(values=c('orange',"red"))

ggsave(p,filename = "../final/figure/pub/fig5c.pdf",width = 5,height = 3)


set.seed(1234)
normal_prep<-caret::createFolds(y= 1:102,k=4)
tumor_prep<-caret::createFolds(y= 1:70,k=4)
out_tab<-data.frame()
db_all=list()
for (i in c(1:4)){
  normal_test_index<-normal_prep[[i]]
  normal_train_index<-setdiff(c(1:102),normal_test_index)
  early_test_index<-tumor_prep[[i]]
  early_train_index<-setdiff(c(1:70),early_test_index)
  
  x_train<-as.matrix(t(cbind(normal_ratio_tab_new2[,normal_train_index],early_ratio_tab_new2[,early_train_index])))
  y_train<-c(rep(0,length(normal_train_index)),rep(1,length(early_train_index)))
  x_test<-as.matrix(t(cbind(normal_ratio_tab_new2[,normal_test_index],early_ratio_tab_new2[,early_test_index])))
  y_test<-c(rep(0,length(normal_test_index)),rep(1,length(early_test_index)))
  elas_fit<-cv.glmnet(x=x_train,y=y_train, family = "binomial",type.measure  = "class", nfolds=5, alpha = 0.1,lambda = seq(0.01,0.05,by = 0.01))
  db_all[[i]]<-elas_fit
  elas_pred_test <- predict(db_all[[i]], newx =x_test, type="response")
  out_tab<-rbind(out_tab,data.frame(score=as.matrix(elas_pred_test)[,1],label=y_test))
}
rownames(sample_info_v2)<-sample_info_v2$Index
out_tab$PSA<-as.numeric(sample_info_v2[rownames(out_tab),"PSA"])
colnames(out_tab)[c(1,2)]<-c("score",'group')


pred <- prediction(as.numeric(as.matrix(out_tab$score)), out_tab$group)
perf <- performance(pred,"tpr","fpr")
roc_obj<-roc(out_tab$group,as.numeric(out_tab$score))
ci_roc<-ci(roc_obj)

plot_tab1<- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),ROC=paste0("PCa test score for all samples,\n",round(ci_roc[2],3)," (",round(ci_roc[1],3),"-",round(ci_roc[3],3),')'))

out_tab2<-subset(out_tab,PSA>4 & PSA<20)

pred <- prediction(as.numeric(as.matrix(out_tab2$score)), out_tab2$group)
perf <- performance(pred,"tpr","fpr")
roc_obj<-roc(out_tab2$group,as.numeric(out_tab2$score))
ci_roc<-ci(roc_obj)

plot_tab2<- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),ROC=paste0("PCa test score for PSA 4-20 samples,\n",round(ci_roc[2],3)," (",round(ci_roc[1],3),"-",round(ci_roc[3],3),')'))


pred <- prediction(as.numeric(as.matrix(out_tab2$PSA)), out_tab2$group)
perf <- performance(pred,"tpr","fpr")
roc_obj<-roc(out_tab2$group,as.numeric(out_tab2$PSA))
ci_roc<-ci(roc_obj)

plot_tab3<- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),ROC=paste0("PSA for PSA 4-20 samples,\n",round(ci_roc[2],3)," (",round(ci_roc[1],3),"-",round(ci_roc[3],3),')'))

plot_tab<-rbind(plot_tab1,plot_tab2,plot_tab3)

p<-ggplot(plot_tab,aes(x=FPR,y=TPR,col=ROC))+geom_line()+scale_color_manual(NULL,values=c(basecol(3)))+mytemp
ggsave(p,filename = "../final/figure/pub/figure4d.pdf",height=4,width=7)

out_tab$group<-factor(out_tab$group,labels = c("non-cancer","non-meta"))
p<-ggplot(out_tab,aes(x=as.factor(group),y=score,col=group))+geom_jitter(width=0.2)+mytemp+ylim(c(0,1))+xlab(NULL)+scale_color_manual(values=c("blue",'red'))
ggsave(p,filename = "../final/figure/pub/figure4e.pdf",width = 5,height = 4)


p_tab<-subset(sample_info_v2,group %in% c("Health","localized","BPH","locally advanced","mHSPC"))
p<-ggplot(p_tab,aes(x=group,y=age,col=group))+geom_boxplot(width=0.7)+geom_jitter(size=1,width=0.2)+mytemp+ylim(c(0,100))+xlab(NULL)+scale_color_manual(values=basecol(5))
ggsave(p,filename= "../final/figure/pub/figureS2_age.pdf",width=7,height = 4)


p<-ggplot(p_tab,aes(x=group,y=PSA,col=group))+geom_boxplot(width=0.7)+geom_jitter(size=1,width=0.2)+mytemp+xlab(NULL)+scale_color_manual(values=basecol(5))+scale_y_log10()
ggsave(p,filename= "../final/figure/pub/figureS2_psa.pdf",width=7,height = 4)

test_sample_info<-read.table("../config/v2p_test_sample_info.txt",sep='\t',header = T)
p_tab<-test_sample_info
p<-ggplot(p_tab,aes(x=group,y=age,col=group))+geom_boxplot(width=0.7)+geom_jitter(size=1,width=0.2)+mytemp+ylim(c(0,100))+xlab(NULL)+scale_color_manual(values=basecol(5))
ggsave(p,filename= "../final/figure/pub/figureS3_age.pdf",width=7,height = 4)


p<-ggplot(p_tab,aes(x=group,y=PSA,col=group))+geom_boxplot(width=0.7)+geom_jitter(size=1,width=0.2)+mytemp+xlab(NULL)+scale_color_manual(values=basecol(5)) #+scale_y_log10()
ggsave(p,filename= "../final/figure/pub/figureS3_psa.pdf",width=7,height = 4)
```

